name: "Deploy blnkns notes"

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy-blnkns-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Upgrade pip
        run: |
          python3 -m pip install --upgrade pip

      - name: Install dependencies
        run: python3 -m pip install -r ./docs/requirements.txt

      - name: Run Makefile
        run: |
          cd docs
          make html

      - name: Run ghp-import
        run: | 
          ghp-import -n -p -f docs/build/html
